/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HQForest.glb 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-fairy-forest-day-07f93a261b674a51816ea67ca6882902
Title: FREE - SkyBox Fairy Forest Day
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HQForest(props) {
  const { nodes, materials } = useGLTF('/HQForest.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Sphere__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={50000} />
      </group>
    </group>
  )
}

useGLTF.preload('/HQForest.glb')
