/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HQSky.glb 
Author: irons3th (https://sketchfab.com/irons3th)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unreal-engine-4-sky-be1fae4d5c6e43bbb4970bde465304d0
Title: Unreal Engine 4 Sky
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HQSky(props) {
  const { nodes, materials } = useGLTF('/HQSky.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.M_Sky_Panning_Clouds2} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/HQSky.glb')
